[2025-03-26T18:31:48.738+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-26T18:31:49.232+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.get_all_data scheduled__2025-03-26T18:00:00+00:00 [queued]>
[2025-03-26T18:31:49.407+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_atropelamento.get_all_data scheduled__2025-03-26T18:00:00+00:00 [queued]>
[2025-03-26T18:31:49.421+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2025-03-26T18:31:49.677+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_all_data> on 2025-03-26 18:00:00+00:00
[2025-03-26T18:31:49.801+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=592) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-26T18:31:49.820+0000] {standard_task_runner.py:72} INFO - Started process 614 to run task
[2025-03-26T18:31:49.941+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_atropelamento', 'get_all_data', 'scheduled__2025-03-26T18:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmpxdd0awgp']
[2025-03-26T18:31:49.977+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask get_all_data
[2025-03-26T18:31:51.024+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_atropelamento.get_all_data scheduled__2025-03-26T18:00:00+00:00 [running]> on host 3a60e3c0d2e4
[2025-03-26T18:31:52.275+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_atropelamento' AIRFLOW_CTX_TASK_ID='get_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-26T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-26T18:00:00+00:00'
[2025-03-26T18:31:52.366+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-26T18:31:52.453+0000] {inaturalist_dag.py:150} INFO - Getting data from keyword: atropelamento
[2025-03-26T18:31:53.952+0000] {inaturalist_dag.py:41} INFO - Maximum id 264497584 for the request
[2025-03-26T18:31:57.190+0000] {job.py:229} INFO - Heartbeat recovered after 11.69 seconds
[2025-03-26T18:31:57.761+0000] {inaturalist_dag.py:58} INFO - Got 0 results
[2025-03-26T18:31:58.532+0000] {inaturalist_dag.py:158} INFO - No more observations found, stopping.
[2025-03-26T18:32:02.360+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-03-26T18:32:03.080+0000] {python.py:240} INFO - Done. Returned value was: []
[2025-03-26T18:32:30.913+0000] {job.py:229} INFO - Heartbeat recovered after 34.42 seconds
[2025-03-26T18:32:35.433+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-26T18:32:36.204+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=get_inaturalist_data_atropelamento, task_id=get_all_data, run_id=scheduled__2025-03-26T18:00:00+00:00, execution_date=20250326T180000, start_date=20250326T183149, end_date=20250326T183236
[2025-03-26T18:32:39.427+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-26T18:32:39.775+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-26T18:32:41.570+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-26T18:32:41.685+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
