[2025-03-25T20:00:04.034+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-25T20:00:04.050+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-25T19:30:00+00:00 [queued]>
[2025-03-25T20:00:04.060+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-25T19:30:00+00:00 [queued]>
[2025-03-25T20:00:04.060+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2025-03-25T20:00:04.069+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): get_all_data> on 2025-03-25 19:30:00+00:00
[2025-03-25T20:00:04.080+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=98) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T20:00:04.087+0000] {standard_task_runner.py:72} INFO - Started process 111 to run task
[2025-03-25T20:00:04.085+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'get_inaturalist_data_roadkill', 'get_all_data', 'scheduled__2025-03-25T19:30:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/inaturalist_dag.py', '--cfg-path', '/tmp/tmp7g9rslau']
[2025-03-25T20:00:04.089+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask get_all_data
[2025-03-25T20:00:04.184+0000] {task_command.py:467} INFO - Running <TaskInstance: get_inaturalist_data_roadkill.get_all_data scheduled__2025-03-25T19:30:00+00:00 [running]> on host 6049b9215306
[2025-03-25T20:00:04.309+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_inaturalist_data_roadkill' AIRFLOW_CTX_TASK_ID='get_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-25T19:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-25T19:30:00+00:00'
[2025-03-25T20:00:04.311+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-25T20:00:04.321+0000] {inaturalist_dag.py:150} INFO - Getting data from keyword: roadkill
[2025-03-25T20:00:04.348+0000] {inaturalist_dag.py:41} INFO - Maximum id 21439887 for the request
[2025-03-25T20:00:11.883+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:00:11.909+0000] {inaturalist_dag.py:163} INFO - Extracted 200 observations
[2025-03-25T20:00:11.910+0000] {inaturalist_dag.py:41} INFO - Maximum id 21448292 for the request
[2025-03-25T20:00:18.615+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:00:18.631+0000] {inaturalist_dag.py:163} INFO - Extracted 400 observations
[2025-03-25T20:00:18.632+0000] {inaturalist_dag.py:41} INFO - Maximum id 21575526 for the request
[2025-03-25T20:00:30.762+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:00:30.798+0000] {inaturalist_dag.py:163} INFO - Extracted 600 observations
[2025-03-25T20:00:30.799+0000] {inaturalist_dag.py:41} INFO - Maximum id 21800619 for the request
[2025-03-25T20:00:45.712+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:00:45.760+0000] {inaturalist_dag.py:163} INFO - Extracted 795 observations
[2025-03-25T20:00:45.760+0000] {inaturalist_dag.py:41} INFO - Maximum id 24471089 for the request
[2025-03-25T20:01:00.418+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:01:00.438+0000] {inaturalist_dag.py:163} INFO - Extracted 993 observations
[2025-03-25T20:01:00.439+0000] {inaturalist_dag.py:41} INFO - Maximum id 26505152 for the request
[2025-03-25T20:01:07.421+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:01:07.437+0000] {inaturalist_dag.py:163} INFO - Extracted 1193 observations
[2025-03-25T20:01:07.437+0000] {inaturalist_dag.py:41} INFO - Maximum id 28642172 for the request
[2025-03-25T20:01:18.950+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:01:18.965+0000] {inaturalist_dag.py:163} INFO - Extracted 1393 observations
[2025-03-25T20:01:18.965+0000] {inaturalist_dag.py:41} INFO - Maximum id 31116302 for the request
[2025-03-25T20:01:30.156+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:01:30.169+0000] {inaturalist_dag.py:163} INFO - Extracted 1592 observations
[2025-03-25T20:01:30.170+0000] {inaturalist_dag.py:41} INFO - Maximum id 33238022 for the request
[2025-03-25T20:01:38.225+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:01:38.253+0000] {inaturalist_dag.py:163} INFO - Extracted 1788 observations
[2025-03-25T20:01:38.254+0000] {inaturalist_dag.py:41} INFO - Maximum id 34906438 for the request
[2025-03-25T20:01:52.043+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:01:52.091+0000] {inaturalist_dag.py:163} INFO - Extracted 1986 observations
[2025-03-25T20:01:52.092+0000] {inaturalist_dag.py:41} INFO - Maximum id 36324919 for the request
[2025-03-25T20:01:57.386+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:01:57.406+0000] {inaturalist_dag.py:163} INFO - Extracted 2184 observations
[2025-03-25T20:01:57.407+0000] {inaturalist_dag.py:41} INFO - Maximum id 36895558 for the request
[2025-03-25T20:02:01.908+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:01.927+0000] {inaturalist_dag.py:163} INFO - Extracted 2379 observations
[2025-03-25T20:02:01.927+0000] {inaturalist_dag.py:41} INFO - Maximum id 37436327 for the request
[2025-03-25T20:02:07.742+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:07.756+0000] {inaturalist_dag.py:163} INFO - Extracted 2579 observations
[2025-03-25T20:02:07.757+0000] {inaturalist_dag.py:41} INFO - Maximum id 37622256 for the request
[2025-03-25T20:02:14.197+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:14.221+0000] {inaturalist_dag.py:163} INFO - Extracted 2779 observations
[2025-03-25T20:02:14.222+0000] {inaturalist_dag.py:41} INFO - Maximum id 38237756 for the request
[2025-03-25T20:02:18.820+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:18.842+0000] {inaturalist_dag.py:163} INFO - Extracted 2979 observations
[2025-03-25T20:02:18.843+0000] {inaturalist_dag.py:41} INFO - Maximum id 38351978 for the request
[2025-03-25T20:02:23.989+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:24.015+0000] {inaturalist_dag.py:163} INFO - Extracted 3179 observations
[2025-03-25T20:02:24.015+0000] {inaturalist_dag.py:41} INFO - Maximum id 38366369 for the request
[2025-03-25T20:02:31.420+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:31.435+0000] {inaturalist_dag.py:163} INFO - Extracted 3379 observations
[2025-03-25T20:02:31.436+0000] {inaturalist_dag.py:41} INFO - Maximum id 38561796 for the request
[2025-03-25T20:02:35.525+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:35.542+0000] {inaturalist_dag.py:163} INFO - Extracted 3579 observations
[2025-03-25T20:02:35.542+0000] {inaturalist_dag.py:41} INFO - Maximum id 38580775 for the request
[2025-03-25T20:02:42.040+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:42.055+0000] {inaturalist_dag.py:163} INFO - Extracted 3779 observations
[2025-03-25T20:02:42.055+0000] {inaturalist_dag.py:41} INFO - Maximum id 38823067 for the request
[2025-03-25T20:02:48.579+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:48.602+0000] {inaturalist_dag.py:163} INFO - Extracted 3979 observations
[2025-03-25T20:02:48.603+0000] {inaturalist_dag.py:41} INFO - Maximum id 39816416 for the request
[2025-03-25T20:02:58.064+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:02:58.077+0000] {inaturalist_dag.py:163} INFO - Extracted 4179 observations
[2025-03-25T20:02:58.078+0000] {inaturalist_dag.py:41} INFO - Maximum id 40387953 for the request
[2025-03-25T20:03:08.601+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:03:08.633+0000] {inaturalist_dag.py:163} INFO - Extracted 4379 observations
[2025-03-25T20:03:08.633+0000] {inaturalist_dag.py:41} INFO - Maximum id 41655977 for the request
[2025-03-25T20:03:17.512+0000] {inaturalist_dag.py:58} INFO - Got 200 results
[2025-03-25T20:03:17.541+0000] {inaturalist_dag.py:163} INFO - Extracted 4579 observations
[2025-03-25T20:03:17.542+0000] {inaturalist_dag.py:41} INFO - Maximum id 42048846 for the request
[2025-03-25T20:03:18.386+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 155, in get_all_data
    last_observation_id, observations_extracted = get_data(maximum_id, api_url)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 53, in get_data
    response = requests.get(api_url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-25T20:03:18.446+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=get_inaturalist_data_roadkill, task_id=get_all_data, run_id=scheduled__2025-03-25T19:30:00+00:00, execution_date=20250325T193000, start_date=20250325T200004, end_date=20250325T200318
[2025-03-25T20:03:18.473+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-25T20:03:18.474+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 65 for task get_all_data (('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')); 111)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 1428, in getresponse
    response.begin()
  File "/usr/local/lib/python3.12/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/http/client.py", line 300, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 155, in get_all_data
    last_observation_id, observations_extracted = get_data(maximum_id, api_url)
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inaturalist_dag.py", line 53, in get_data
    response = requests.get(api_url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[2025-03-25T20:03:18.530+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-25T20:03:18.551+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-25T20:03:18.552+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
